name: thesis_app
description: "thesis project"
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  flutter_bloc: ^8.1.2
  freezed_annotation: ^2.2.0
  json_annotation: ^4.9.0
  injectable: ^2.1.4
  get_it: ^7.2.0
  mocktail: ^1.0.4
  bloc_test: ^9.1.7
  flutter_svg: ^2.0.17
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  injectable_generator: ^2.1.4
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.1

flutter:
  uses-material-design: true

  assets:
    - assets/themes/

  fonts:
    - family: ClashDisplay
      fonts:
        - asset: assets/fonts/ClashDisplay-Extralight.otf
          weight: 200
        - asset: assets/fonts/ClashDisplay-Light.otf
          weight: 300
        - asset: assets/fonts/ClashDisplay-Regular.otf
          weight: 400
        - asset: assets/fonts/ClashDisplay-Medium.otf
          weight: 500
        - asset: assets/fonts/ClashDisplay-Semibold.otf
          weight: 600
        - asset: assets/fonts/ClashDisplay-Bold.otf
          weight: 700
